In [1]:
import gymnasium as gym
from ppo_agent import PPOAgent
import tensorflow as tf

KeyboardInterrupt: 

In [ ]:
env = gym.make('CartPole-v0', render_mode='rgb_array')
config = {
        'clip_param': 0.2,
        'activation': 'relu',
        'kernel_initializer': 'orthogonal',
        'actor_optimizer': tf.keras.optimizers.legacy.Adam,
        'critic_optimizer': tf.keras.optimizers.legacy.Adam,
        'actor_learning_rate': 0.005,
        'critic_learning_rate': 0.005,
        'actor_epsilon': 1e-7,
        'critic_epsilon': 1e-7,
        'actor_clipnorm': 0.5,
        'critic_clipnorm': 0.5,
        # NORMALIZATION?
        # 'n_step': 3,
        'discount_factor': 0.99,
        'gae_lambda': 0.98,
        'conv_layers': [],
        'conv_layers_noisy': False,
        'critic_width': 64,
        'critic_dense_layers': 2,
        'critic_dense_layers_noisy': False,
        'actor_width': 64,
        'actor_dense_layers': 2,
        'actor_dense_layers_noisy': False,
        # REWARD CLIPPING
        'noisy_sigma': 0.5, #
        'loss_function': tf.keras.losses.KLDivergence(),
        'num_epochs': 30,
        'steps_per_epoch': 4800,
        'train_policy_iterations': 5,
        'train_value_iterations': 5,
        # 'per_epsilon': 0.001,
        # 'per_alpha': 0.5,
        # 'per_beta': 0.5,
        'target_kl': 0.02,
        # 'per_beta_increase': hp.uniform('per_beta_increase', 0, 0.015),
        # 'v_min': -500.0, # MIN GAME SCORE
        # 'v_max': 500.0, # MAX GAME SCORE
        # 'search_max_depth': 5,
        # 'search_max_time': 10,
    }

agent = PPOAgent(env, config=config)


In [ ]:
# agent.actor.summary()

In [ ]:
# state, _ = env.reset()
# print(state)
# print(agent.select_action(state)[0])
agent.train()

tf.Tensor([ 1.4094198  1.3372362  1.2624757 ... -1.5804867 -1.5804867 -1.5804867], shape=(4800,), dtype=float32) tf.Tensor([ 1.1748812  1.110722   1.0527692 ... -1.9702953 -1.9768041 -1.9706832], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4094198  1.3372362  1.2624757 ... -1.5804867 -1.5804867 -1.5804867], shape=(4800,), dtype=float32) tf.Tensor([ 1.1830596  1.1172154  1.0614324 ... -1.9881711 -1.9763654 -1.9899977], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4094198  1.3372362  1.2624757 ... -1.5804867 -1.5804867 -1.5804867], shape=(4800,), dtype=float32) tf.Tensor([ 1.1897844  1.1257167  1.0686144 ... -2.0088978 -1.9714442 -2.0123518], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4094198  1.3372362  1.2624757 ... -1.5804867 -1.5804867 -1.5804867], shape=(4800,), dtype=float32) tf.Tensor([ 1.1988415  1.1345356  1.0773462 ... -2.0322766 -1.9655105 -2.0374796], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4094198  1.3372362  1.2624757 ... -1.5804867 -1.5804867 -1.5804867], shape=(4800,)

C:\Users\adria\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gymnasium\wrappers\record_video.py:94: UserWarning: WARN: Overwriting existing videos at c:\Users\adria\OneDrive\Documents\rl-research\ppo\videos\1709512150.134112 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


Moviepy - Building video c:\Users\adria\OneDrive\Documents\rl-research\ppo\videos\1709512150.134112\rl-video-episode-0.mp4.
Moviepy - Writing video c:\Users\adria\OneDrive\Documents\rl-research\ppo\videos\1709512150.134112\rl-video-episode-0.mp4



TypeError: must be real number, not NoneType

In [ ]:
agent.test()

Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1.mp4
score:  112.0
score:  152.0
score:  50.0
score:  115.0
score:  137.0
score:  32.0
score:  119.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-8.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-8.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-8.mp4
score:  113.0
score:  154.0
score:  117.0
score:  22.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-512.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-512.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-512.mp4
score:  146.0
score:  118.0
score:  112.0
score:  158.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-216.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-216.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-216.mp4
score:  86.0
score:  111.0
score:  158.0
score:  127.0
score:  46.0
score:  140.0
score:  108.0
score:  125.0
score:  117.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-125.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-125.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-125.mp4
score:  127.0
score:  143.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-27.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-27.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-27.mp4
score:  48.0


score:  120.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-729.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-729.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-729.mp4
score:  104.0
score:  159.0
score:  66.0
score:  104.0
score:  114.0
score:  147.0
score:  98.0
score:  153.0
score:  80.0
score:  67.0
score:  190.0
score:  135.0
score:  59.0
score:  193.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-343.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-343.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-343.mp4
score:  143.0
score:  109.0
score:  105.0
score:  173.0
score:  93.0
score:  111.0
score:  129.0
score:  149.0
score:  142.0
score:  133.0
score:  128.0
score:  151.0
score:  27.0
score:  163.0
score:  65.0
score:  111.0
score:  200.0
score:  101.0
score:  84.0
score:  119.0
score:  158.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-64.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-64.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-64.mp4
score:  100.0
score:  200.0
score:  31.0
score:  118.0
score:  119.0
score:  121.0
score:  99.0
score:  71.0
score:  83.0
score:  174.0
score:  150.0
score:  107.0
score:  78.0
score:  82.0
score:  106.0
score:  48.0
score:  114.0
score:  103.0
score:  155.0
score:  90.0
score:  104.0
score:  147.0
score:  61.0
score:  141.0
score:  185.0
score:  105.0
score:  181.0
score:  121.0
score:  155.0
score:  89.0
score:  169.0
score:  69.0
score:  200.0
score:  128.0
score:  158.0
score:  200.0


/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-3000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-3000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-3000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-2000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-2000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-2000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-0.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-0.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-0.mp4
score:  127.0


118.65

In [ ]:
import tensorflow_probability as tfp

print(tf.one_hot([0, 1, 1], 2))
distribution = tfp.distributions.Categorical(probs=[[0.1, 0.9],[0.9, 0.1]])
print(distribution.sample())
print(tf.reduce_sum(tf.reduce_mean([-0.6, -0.6] - distribution.log_prob([1, 0]))))
print(tf.reduce_mean([-0.6, -0.6] - tf.reduce_sum(tf.one_hot([1, 0], 2) * tf.math.log([[0.1, 0.9],[0.9, 0.1]]), axis=1)))

print(tf.math.log(tf.nn.softmax([[0.1, 0.9],[0.9, 0.1]])))
print(tf.nn.log_softmax([[0.1, 0.9],[0.9, 0.1]]))

def logprobabilities(logits, a):
    # Compute the log-probabilities of taking actions a by using the logits (i.e. the output of the actor)
    logprobabilities_all = tf.math.log(logits)
    logprobability = tf.reduce_sum(
        tf.one_hot(a, 2) * logprobabilities_all, axis=1
    )
    return logprobability


kl = tf.reduce_mean(
[-0.6, -0.6] - logprobabilities([[0.1, 0.9], [0.9, 0.1]], [1, 0])
)
# kl = tf.reduce_sum(kl)
print(kl)


tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int32)
tf.Tensor(-0.49463958, shape=(), dtype=float32)
tf.Tensor(-0.4946395, shape=(), dtype=float32)
tf.Tensor(
[[-1.1711006  -0.37110066]
 [-0.37110066 -1.1711006 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.1711006  -0.37110063]
 [-0.37110063 -1.1711006 ]], shape=(2, 2), dtype=float32)
tf.Tensor(-0.4946395, shape=(), dtype=float32)
