In [5]:
import gymnasium as gym
from ppo_agent import PPOAgent
import tensorflow as tf

In [6]:
env = gym.make('CartPole-v0', render_mode='rgb_array')
config = {
        'clip_param': 0.2,
        'activation': 'relu',
        'kernel_initializer': 'orthogonal',
        'actor_optimizer': tf.keras.optimizers.legacy.Adam,
        'critic_optimizer': tf.keras.optimizers.legacy.Adam,
        'actor_learning_rate': 0.005,
        'critic_learning_rate': 0.005,
        'actor_epsilon': 1e-7,
        'critic_epsilon': 1e-7,
        'actor_clipnorm': 0.5,
        'critic_clipnorm': 0.5,
        # NORMALIZATION?
        # 'n_step': 3,
        'discount_factor': 0.99,
        'gae_lambda': 0.98,
        'conv_layers': [],
        'conv_layers_noisy': False,
        'critic_width': 64,
        'critic_dense_layers': 2,
        'critic_dense_layers_noisy': False,
        'actor_width': 64,
        'actor_dense_layers': 2,
        'actor_dense_layers_noisy': False,
        # REWARD CLIPPING
        'noisy_sigma': 0.5, #
        'loss_function': tf.keras.losses.KLDivergence(),
        'num_epochs': 30,
        'steps_per_epoch': 4800,
        'train_policy_iterations': 5,
        'train_value_iterations': 5,
        # 'per_epsilon': 0.001,
        # 'per_alpha': 0.5,
        # 'per_beta': 0.5,
        'target_kl': 0.02,
        # 'per_beta_increase': hp.uniform('per_beta_increase', 0, 0.015),
        # 'v_min': -500.0, # MIN GAME SCORE
        # 'v_max': 500.0, # MAX GAME SCORE
        # 'search_max_depth': 5,
        # 'search_max_time': 10,
    }

agent = PPOAgent(env, config=config)


/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/envs/registration.py:513: DeprecationWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.deprecation(


In [7]:
# agent.actor.summary()

In [8]:
# state, _ = env.reset()
# print(state)
# print(agent.select_action(state)[0])
agent.train()

tf.Tensor(
[ 0.36546305  0.22088398  0.06850814 ... -1.6089028  -1.6089028
 -1.6089028 ], shape=(4800,), dtype=float32) tf.Tensor(
[ 0.30458584  0.18399036  0.05708157 ... -2.0129972  -2.0136743
 -2.0076704 ], shape=(4800,), dtype=float32)
tf.Tensor(
[ 0.36546305  0.22088398  0.06850814 ... -1.6089028  -1.6089028
 -1.6089028 ], shape=(4800,), dtype=float32) tf.Tensor(
[ 0.3031965   0.185576    0.05736025 ... -1.9922944  -1.9846159
 -2.044555  ], shape=(4800,), dtype=float32)
tf.Tensor(
[ 0.36546305  0.22088398  0.06850814 ... -1.6089028  -1.6089028
 -1.6089028 ], shape=(4800,), dtype=float32) tf.Tensor(
[ 0.3013255   0.18766122  0.05773509 ... -1.9653136  -1.9473603
 -2.0920937 ], shape=(4800,), dtype=float32)
tf.Tensor(
[ 0.36546305  0.22088398  0.06850814 ... -1.6089028  -1.6089028
 -1.6089028 ], shape=(4800,), dtype=float32) tf.Tensor(
[ 0.2989708   0.19026071  0.05821752 ... -1.9320759  -1.9018408
 -2.149287  ], shape=(4800,), dtype=float32)
tf.Tensor(
[ 0.36546305  0.22088398  0.0

/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
t:   9%|▉         | 1/11 [01:52<18:47, 112.75s/it, now=None]

Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-0.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-0.mp4



t:   9%|▉         | 1/11 [01:53<18:50, 113.00s/it, now=None]

Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-0.mp4
score:  14.0
tf.Tensor([ 1.4844472  1.4324844  1.4172541 ... -1.9798962 -1.9798962 -1.9798962], shape=(4800,), dtype=float32) tf.Tensor([ 1.1989799  1.1817034  1.1480271 ... -2.6789606 -2.265665  -2.6947875], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4844472  1.4324844  1.4172541 ... -1.9798962 -1.9798962 -1.9798962], shape=(4800,), dtype=float32) tf.Tensor([ 1.2040153  1.1977923  1.1514115 ... -2.620296  -2.327886  -2.6310253], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4844472  1.4324844  1.4172541 ... -1.9798962 -1.9798962 -1.9798962], shape=(4800,), dtype=float32) tf.Tensor([ 1.2117697  1.215758   1.1570075 ... -2.54546   -2.4022543 -2.551011 ], shape=(4800,), dtype=float32)
tf.Tensor([ 1.4844472  1.4324844  1.4172541 ... -1.9798962 -1.9798962 -1.9798962], shape=(4800,), dtype=float32) tf.Tensor([ 1.2217067  1.2365044  1.1644317 ...

t:   9%|▉         | 1/11 [02:42<27:08, 162.83s/it, now=None]

Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-1.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-1.mp4



t:   9%|▉         | 1/11 [02:43<27:11, 163.11s/it, now=None]

Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-1.mp4
score:  34.0
score:  31.0
score:  24.0
score:  93.0
score:  41.0
score:  35.0
score:  20.0


t:   9%|▉         | 1/11 [02:46<27:40, 166.04s/it, now=None]

Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-8.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-8.mp4



t:   9%|▉         | 1/11 [02:46<27:42, 166.23s/it, now=None]

Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709505540.694938/rl-video-episode-8.mp4
score:  50.0
score:  20.0
score:  139.0
score:  46.0
score:  55.0
score:  31.0


In [ ]:
agent.test()

Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1.mp4
score:  112.0
score:  152.0
score:  50.0
score:  115.0
score:  137.0
score:  32.0
score:  119.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-8.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-8.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-8.mp4
score:  113.0
score:  154.0
score:  117.0
score:  22.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-512.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-512.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-512.mp4
score:  146.0
score:  118.0
score:  112.0
score:  158.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-216.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-216.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-216.mp4
score:  86.0
score:  111.0
score:  158.0
score:  127.0
score:  46.0
score:  140.0
score:  108.0
score:  125.0
score:  117.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-125.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-125.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-125.mp4
score:  127.0
score:  143.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-27.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-27.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-27.mp4
score:  48.0


score:  120.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-729.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-729.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-729.mp4
score:  104.0
score:  159.0
score:  66.0
score:  104.0
score:  114.0
score:  147.0
score:  98.0
score:  153.0
score:  80.0
score:  67.0
score:  190.0
score:  135.0
score:  59.0
score:  193.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-343.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-343.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-343.mp4
score:  143.0
score:  109.0
score:  105.0
score:  173.0
score:  93.0
score:  111.0
score:  129.0
score:  149.0
score:  142.0
score:  133.0
score:  128.0
score:  151.0
score:  27.0
score:  163.0
score:  65.0
score:  111.0
score:  200.0
score:  101.0
score:  84.0
score:  119.0
score:  158.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-64.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-64.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-64.mp4
score:  100.0
score:  200.0
score:  31.0
score:  118.0
score:  119.0
score:  121.0
score:  99.0
score:  71.0
score:  83.0
score:  174.0
score:  150.0
score:  107.0
score:  78.0
score:  82.0
score:  106.0
score:  48.0
score:  114.0
score:  103.0
score:  155.0
score:  90.0
score:  104.0
score:  147.0
score:  61.0
score:  141.0
score:  185.0
score:  105.0
score:  181.0
score:  121.0
score:  155.0
score:  89.0
score:  169.0
score:  69.0
score:  200.0
score:  128.0
score:  158.0
score:  200.0


/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-3000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-3000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-3000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-2000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-2000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-2000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-1000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-0.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-0.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709489411.926007/rl-video-episode-0.mp4
score:  127.0


118.65

In [ ]:
import tensorflow_probability as tfp

print(tf.one_hot([0, 1, 1], 2))
distribution = tfp.distributions.Categorical(probs=[[0.1, 0.9],[0.9, 0.1]])
print(distribution.sample())
print(tf.reduce_sum(tf.reduce_mean([-0.6, -0.6] - distribution.log_prob([1, 0]))))
print(tf.reduce_mean([-0.6, -0.6] - tf.reduce_sum(tf.one_hot([1, 0], 2) * tf.math.log([[0.1, 0.9],[0.9, 0.1]]), axis=1)))

print(tf.math.log(tf.nn.softmax([[0.1, 0.9],[0.9, 0.1]])))
print(tf.nn.log_softmax([[0.1, 0.9],[0.9, 0.1]]))

def logprobabilities(logits, a):
    # Compute the log-probabilities of taking actions a by using the logits (i.e. the output of the actor)
    logprobabilities_all = tf.math.log(logits)
    logprobability = tf.reduce_sum(
        tf.one_hot(a, 2) * logprobabilities_all, axis=1
    )
    return logprobability


kl = tf.reduce_mean(
[-0.6, -0.6] - logprobabilities([[0.1, 0.9], [0.9, 0.1]], [1, 0])
)
# kl = tf.reduce_sum(kl)
print(kl)


tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int32)
tf.Tensor(-0.49463958, shape=(), dtype=float32)
tf.Tensor(-0.4946395, shape=(), dtype=float32)
tf.Tensor(
[[-1.1711006  -0.37110066]
 [-0.37110066 -1.1711006 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.1711006  -0.37110063]
 [-0.37110063 -1.1711006 ]], shape=(2, 2), dtype=float32)
tf.Tensor(-0.4946395, shape=(), dtype=float32)
