In [1]:
import gymnasium as gym
from ppo_agent import PPOAgent
import tensorflow as tf

/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


1 Physical GPUs, 1 Logical GPUs


2024-03-04 02:10:32.216858: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2024-03-04 02:10:32.216883: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-03-04 02:10:32.216891: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-03-04 02:10:32.217203: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-03-04 02:10:32.217567: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [2]:
env = gym.make('CartPole-v1', render_mode='rgb_array')
config = {
        'clip_param': 0.2,
        'activation': 'relu',
        'kernel_initializer': 'orthogonal',
        'actor_optimizer': tf.keras.optimizers.legacy.Adam,
        'critic_optimizer': tf.keras.optimizers.legacy.Adam,
        'actor_learning_rate': 0.005,
        'critic_learning_rate': 0.005,
        'actor_epsilon': 1e-7,
        'critic_epsilon': 1e-7,
        'actor_clipnorm': 0.5,
        'critic_clipnorm': 0.5,
        # NORMALIZATION?
        # 'n_step': 3,
        'discount_factor': 0.99,
        'gae_lambda': 0.98,
        'conv_layers': [],
        'conv_layers_noisy': False,
        'critic_width': 64,
        'critic_dense_layers': 2,
        'critic_dense_layers_noisy': False,
        'actor_width': 64,
        'actor_dense_layers': 2,
        'actor_dense_layers_noisy': False,
        # REWARD CLIPPING
        'noisy_sigma': 0.5, #
        'loss_function': tf.keras.losses.KLDivergence(),
        'num_epochs': 30,
        'steps_per_epoch': 4800,
        'train_policy_iterations': 5,
        'train_value_iterations': 5,
        'target_kl': 0.02,
        'entropy_coefficient': 0.01,
        'num_minibatches': 4,
        # 'per_epsilon': 0.001,
        # 'per_alpha': 0.5,
        # 'per_beta': 0.5,
        # 'per_beta_increase': hp.uniform('per_beta_increase', 0, 0.015),
        # 'v_min': -500.0, # MIN GAME SCORE
        # 'v_max': 500.0, # MAX GAME SCORE
        # 'search_max_depth': 5,
        # 'search_max_time': 10,
    }

agent = PPOAgent(env, config=config)


In [3]:
# agent.actor.summary()

In [4]:
# state, _ = env.reset()
# print(state)
# print(agent.select_action(state)[0])
agent.train()

score:  38.0
score:  52.0
score:  68.0
score:  70.0
score:  22.0
score:  37.0


KeyboardInterrupt: 

In [ ]:
agent.test()

Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-1.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-1.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-1.mp4
score:  152.0
score:  330.0
score:  290.0
score:  149.0
score:  275.0
score:  245.0
score:  170.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-8.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-8.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-8.mp4
score:  371.0
score:  176.0
score:  174.0
score:  225.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-512.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-512.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-512.mp4
score:  188.0
score:  191.0
score:  179.0
score:  131.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-216.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-216.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-216.mp4
score:  197.0
score:  153.0
score:  218.0
score:  500.0
score:  188.0
score:  243.0
score:  451.0
score:  230.0
score:  158.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-125.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-125.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-125.mp4
score:  237.0
score:  166.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-27.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-27.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-27.mp4
score:  308.0
score:  136.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-729.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-729.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-729.mp4
score:  174.0
score:  173.0
score:  184.0
score:  289.0
score:  153.0
score:  192.0
score:  304.0
score:  140.0
score:  152.0
score:  178.0
score:  162.0
score:  291.0
score:  144.0
score:  200.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-343.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-343.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-343.mp4
score:  144.0
score:  197.0
score:  331.0
score:  158.0
score:  151.0
score:  155.0
score:  271.0
score:  182.0
score:  361.0
score:  201.0
score:  145.0
score:  170.0
score:  225.0
score:  158.0
score:  243.0
score:  159.0
score:  178.0
score:  200.0
score:  219.0
score:  301.0
score:  362.0
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-64.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-64.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-64.mp4
score:  145.0
score:  149.0
score:  173.0
score:  160.0
score:  178.0
score:  144.0
score:  151.0
score:  144.0
score:  138.0
score:  159.0
score:  178.0
score:  190.0
score:  308.0
score:  168.0
score:  218.0
score:  170.0
score:  268.0
score:  154.0
score:  190.0
score:  183.0
score:  336.0
score:  166.0
score:  361.0
score:  238.0
score:  274.0
score:  500.0
score:  155.0
score:  288.0
score:  184.0
score:  287.0
score:  400.0
score:  187.0
score:  199.0
score:  159.0
score:  234.0
score:  218.0


/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061 folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-3000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-3000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-3000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-2000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-2000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-2000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-1000.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-1000.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-1000.mp4
Moviepy - Building video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-0.mp4.
Moviepy - Writing video /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-0.mp4



Moviepy - Done !
Moviepy - video ready /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/ppo/videos/1709520406.106061/rl-video-episode-0.mp4
score:  157.0


215.89

In [ ]:
import tensorflow_probability as tfp

print(tf.one_hot([0, 1, 1], 2))
distribution = tfp.distributions.Categorical(probs=[[0.1, 0.9],[0.9, 0.1]])
print(distribution.sample())
print(tf.reduce_sum(tf.reduce_mean([-0.6, -0.6] - distribution.log_prob([1, 0]))))
print(tf.reduce_mean([-0.6, -0.6] - tf.reduce_sum(tf.one_hot([1, 0], 2) * tf.math.log([[0.1, 0.9],[0.9, 0.1]]), axis=1)))

print(tf.math.log(tf.nn.softmax([[0.1, 0.9],[0.9, 0.1]])))
print(tf.nn.log_softmax([[0.1, 0.9],[0.9, 0.1]]))

def logprobabilities(logits, a):
    # Compute the log-probabilities of taking actions a by using the logits (i.e. the output of the actor)
    logprobabilities_all = tf.math.log(logits)
    logprobability = tf.reduce_sum(
        tf.one_hot(a, 2) * logprobabilities_all, axis=1
    )
    return logprobability


kl = tf.reduce_mean(
[-0.6, -0.6] - logprobabilities([[0.1, 0.9], [0.9, 0.1]], [1, 0])
)
# kl = tf.reduce_sum(kl)
print(kl)


tf.Tensor(
[[1. 0.]
 [0. 1.]
 [0. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor(-0.49463958, shape=(), dtype=float32)
tf.Tensor(-0.4946395, shape=(), dtype=float32)
tf.Tensor(
[[-1.1711006  -0.37110066]
 [-0.37110066 -1.1711006 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.1711006  -0.37110063]
 [-0.37110063 -1.1711006 ]], shape=(2, 2), dtype=float32)
tf.Tensor(-0.4946395, shape=(), dtype=float32)


In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr.reshape(3, 3))
arr = np.rot90(arr.reshape(3, 3), k=2)
print(arr)
arr = arr.flatten()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[9 8 7 6 5 4 3 2 1]
