In [2]:
import numpy as np
indices = np.random.choice(10, 5, replace=True)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[indices])
print(arr[-11:])
reward_buffer = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -1]
size = 7
game_start_index = 0
reward = reward_buffer[size - 1]
updated_rewards = np.empty((size - game_start_index,), int)
updated_rewards[::2] = 1 * reward
updated_rewards[1::2] = -1 * reward
updated_rewards = np.flip(updated_rewards)
print(updated_rewards)
reward_buffer[game_start_index:size] = updated_rewards
print(reward_buffer)
game_start_index = 7
size = 15
print(len(reward_buffer))
reward = reward_buffer[size - 1]
updated_rewards = np.empty((size - game_start_index,), int)
updated_rewards[::2] = 1 * reward
updated_rewards[1::2] = -1 * reward
updated_rewards = np.flip(updated_rewards)
print(updated_rewards)
reward_buffer[game_start_index:size] = updated_rewards
print(reward_buffer)
print(len(reward_buffer))
overflow_reward = 1
overflow_count = 1

[10  9  3 10  6]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1 -1  1 -1  1 -1  1]
[1, -1, 1, -1, 1, -1, 1, 0, 0, 0, 0, 0, 0, 0, -1]
15
[ 1 -1  1 -1  1 -1  1 -1]
[1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, -1]
15


In [3]:
# reward_buffer = np.array([1, -1, 1, -1, 1, -1, 0])
# reward_buffer[6] = [1, 1, 1, 1]
# print(reward_buffer)

In [4]:
from alphazero_agent import AlphaZeroAgent
import gymnasium as gym 
import tensorflow as tf
import gym_tictactoe
import numpy as np

class ClipReward(gym.RewardWrapper):
    def __init__(self, env, min_reward, max_reward):
        super().__init__(env)
        self.min_reward = min_reward
        self.max_reward = max_reward
        self.reward_range = (min_reward, max_reward)

    def reward(self, reward):
        return np.clip(reward, self.min_reward, self.max_reward)


env = ClipReward(gym.wrappers.AtariPreprocessing(gym.make("MsPacmanNoFrameskip-v4", render_mode="rgb_array"), terminal_on_life_loss=True), -1, 1) # as recommended by the original paper, should already include max pooling
# env = gym.make("environments/TicTacToe-v0")
env = gym.wrappers.FrameStack(env, 4)

config = {
        'activation': 'relu',
        'kernel_initializer': 'orthogonal',
        'optimizer_function': tf.keras.optimizers.legacy.Adam,
        'learning_rate': 0.2,
        'adam_epsilon': 1e-7,
        'clipnorm': 0.5,
        # NORMALIZATION?
        # REWARD CLIPPING
        'num_epochs': 30,
        'num_filters': 256,
        'kernel_size': 3,
        'stride': 1,
        'num_res_blocks': 5,
        'critic_hidden_filters': 256,
        'critic_dense_size': 256,
        'actor_hidden_filters': 256,
        'actor_dense_size': 256,
        'memory_size': 10000,
        'max_game_length': 1000,
        'batch_size': 10,
        'dirichlet_alpha': 0.3,
        'dirichlet_epsilon': 0.25,
        'c_puct': 1,
        'monte_carlo_simulations': 10,
        'two_player': False,
    }    



KeyboardInterrupt: 

In [ ]:
agent = AlphaZeroAgent(env, config=config)
agent.train()

/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


Step 1
MCTS Simulation 0
MCTS Simulation 1
[0.14119078 0.1338523  0.14152081 0.06208776 0.06568136 0.11493241
 0.1633879  0.10611935 0.07122732] [-0.01116458]
MCTS Simulation 2
[0.13995424 0.13492715 0.14072299 0.06261072 0.06455637 0.1129489
 0.1648322  0.10738961 0.07205782] [0.00368449]
MCTS Simulation 3
[0.1376529  0.13485743 0.14060876 0.06358535 0.06498847 0.11263786
 0.16518855 0.10927252 0.07120822] [-0.01899016]
MCTS Simulation 4
[0.13555692 0.13221689 0.14553586 0.06278828 0.06353899 0.11559899
 0.16595273 0.10853655 0.07027475] [-0.01886977]
MCTS Simulation 5
[0.13659689 0.13377567 0.14190787 0.06274069 0.06357504 0.11413016
 0.1661532  0.11058651 0.07053395] [-0.02175643]
MCTS Simulation 6
[0.13897392 0.13246937 0.14321798 0.062179   0.0641829  0.11476596
 0.1657513  0.10775495 0.07070465] [-0.01062614]
MCTS Simulation 7
[0.13634029 0.13306357 0.14262074 0.06299547 0.06349854 0.11414465
 0.16694124 0.11007079 0.07032468] [-0.02056944]
MCTS Simulation 8
[0.13634029 0.1330635

KeyboardInterrupt: 

In [ ]:
array = np.zeros((3, 9))
array[0] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(array)

In [7]:
import gym_envs
import gymnasium as gym
env = gym.make('gym_envs/GridWorld-v0', render_mode='human')

env.reset()
for i in range(10):
    env.step(0)
    env.render()
