In [1]:
import numpy as np
indices = np.random.choice(10, 5, replace=True)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[indices])
print(arr[-11:])
reward_buffer = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -1]
size = 7
game_start_index = 0
reward = reward_buffer[size - 1]
updated_rewards = np.empty((size - game_start_index,), int)
updated_rewards[::2] = 1 * reward
updated_rewards[1::2] = -1 * reward
updated_rewards = np.flip(updated_rewards)
print(updated_rewards)
reward_buffer[game_start_index:size] = updated_rewards
print(reward_buffer)
game_start_index = 7
size = 15
print(len(reward_buffer))
reward = reward_buffer[size - 1]
updated_rewards = np.empty((size - game_start_index,), int)
updated_rewards[::2] = 1 * reward
updated_rewards[1::2] = -1 * reward
updated_rewards = np.flip(updated_rewards)
print(updated_rewards)
reward_buffer[game_start_index:size] = updated_rewards
print(reward_buffer)
print(len(reward_buffer))
overflow_reward = 1
overflow_count = 1

[7 8 5 9 4]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1 -1  1 -1  1 -1  1]
[1, -1, 1, -1, 1, -1, 1, 0, 0, 0, 0, 0, 0, 0, -1]
15
[ 1 -1  1 -1  1 -1  1 -1]
[1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, -1]
15


In [2]:
# reward_buffer = np.array([1, -1, 1, -1, 1, -1, 0])
# reward_buffer[6] = [1, 1, 1, 1]
# print(reward_buffer)

In [3]:
from alphazero_agent import AlphaZeroAgent
import gymnasium as gym 
import tensorflow as tf
import environments

class ClipReward(gym.RewardWrapper):
    def __init__(self, env, min_reward, max_reward):
        super().__init__(env)
        self.min_reward = min_reward
        self.max_reward = max_reward
        self.reward_range = (min_reward, max_reward)

    def reward(self, reward):
        return np.clip(reward, self.min_reward, self.max_reward)


env = ClipReward(gym.wrappers.AtariPreprocessing(gym.make("MsPacmanNoFrameskip-v4", render_mode="rgb_array"), terminal_on_life_loss=True), -1, 1) # as recommended by the original paper, should already include max pooling
# env = gym.make("environments/TicTacToe-v0")
env = gym.wrappers.FrameStack(env, 4)

config = {
        'activation': 'relu',
        'kernel_initializer': 'orthogonal',
        'optimizer_function': tf.keras.optimizers.legacy.Adam,
        'learning_rate': 0.2,
        'adam_epsilon': 1e-7,
        'clipnorm': 0.5,
        # NORMALIZATION?
        # REWARD CLIPPING
        'num_epochs': 30,
        'num_filters': 256,
        'kernel_size': 3,
        'stride': 1,
        'num_res_blocks': 5,
        'critic_hidden_filters': 256,
        'critic_dense_size': 256,
        'actor_hidden_filters': 256,
        'actor_dense_size': 256,
        'memory_size': 10000,
        'max_game_length': 1000,
        'batch_size': 10,
        'dirichlet_alpha': 0.3,
        'dirichlet_epsilon': 0.25,
        'c_puct': 1,
        'monte_carlo_simulations': 10,
        'two_player': False,
    }    

agent = AlphaZeroAgent(env, config=config)

/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


1 Physical GPUs, 1 Logical GPUs


2024-03-05 00:51:32.123245: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2024-03-05 00:51:32.123267: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-03-05 00:51:32.123272: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-03-05 00:51:32.123307: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-03-05 00:51:32.123326: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]


In [4]:
agent.train()

MCTS Simulation 0
MCTS Simulation 1
[0.09003669 0.09345073 0.14901456 0.09909695 0.0891524  0.14801739
 0.11857633 0.09555581 0.1170992 ] [0.04565001]
MCTS Simulation 2
[0.08848656 0.09444994 0.14721942 0.09845119 0.09161873 0.14929579
 0.11888085 0.09393676 0.1176608 ] [0.06462094]
MCTS Simulation 3
[0.08997522 0.09312855 0.1469905  0.09779449 0.09219749 0.14899631
 0.11960631 0.09372113 0.11758999] [0.05624504]
MCTS Simulation 4
[0.09034494 0.09355255 0.14682896 0.0970395  0.09170025 0.15040755
 0.11907396 0.0934835  0.11756881] [0.06352325]
MCTS Simulation 5
[0.08963403 0.09382261 0.14986756 0.09843018 0.09111176 0.14485204
 0.12027548 0.09357978 0.11842652] [0.04593396]
MCTS Simulation 6
[0.08884358 0.09317438 0.14950845 0.09664876 0.0933664  0.14620367
 0.11911076 0.0935545  0.11958947] [0.05896797]
MCTS Simulation 7
[0.09003669 0.09345073 0.14901456 0.09909695 0.0891524  0.14801739
 0.11857633 0.09555581 0.1170992 ] [0.04565001]
MCTS Simulation 8
[0.0894814  0.09439033 0.14738505

KeyboardInterrupt: 

In [ ]:
array = np.zeros((3, 9))
array[0] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(array)

[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
