In [1]:
import numpy as np
indices = np.random.choice(10, 5, replace=True)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[indices])
print(arr[-11:])
reward_buffer = [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, -1]
size = 7
game_start_index = 0
reward = reward_buffer[size - 1]
updated_rewards = np.empty((size - game_start_index,), int)
updated_rewards[::2] = 1 * reward
updated_rewards[1::2] = -1 * reward
updated_rewards = np.flip(updated_rewards)
print(updated_rewards)
reward_buffer[game_start_index:size] = updated_rewards
print(reward_buffer)
game_start_index = 7
size = 15
print(len(reward_buffer))
reward = reward_buffer[size - 1]
updated_rewards = np.empty((size - game_start_index,), int)
updated_rewards[::2] = 1 * reward
updated_rewards[1::2] = -1 * reward
updated_rewards = np.flip(updated_rewards)
print(updated_rewards)
reward_buffer[game_start_index:size] = updated_rewards
print(reward_buffer)
print(len(reward_buffer))
overflow_reward = 1
overflow_count = 1

[10 10  2  2 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1 -1  1 -1  1 -1  1]
[1, -1, 1, -1, 1, -1, 1, 0, 0, 0, 0, 0, 0, 0, -1]
15
[ 1 -1  1 -1  1 -1  1 -1]
[1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, -1]
15


In [2]:
# reward_buffer = np.array([1, -1, 1, -1, 1, -1, 0])
# reward_buffer[6] = [1, 1, 1, 1]
# print(reward_buffer)

In [4]:
from alphazero_agent import AlphaZeroAgent
import gymnasium as gym 
import tensorflow as tf
import numpy as np

class ClipReward(gym.RewardWrapper):
    def __init__(self, env, min_reward, max_reward):
        super().__init__(env)
        self.min_reward = min_reward
        self.max_reward = max_reward
        self.reward_range = (min_reward, max_reward)

    def reward(self, reward):
        return np.clip(reward, self.min_reward, self.max_reward)


env = ClipReward(gym.wrappers.AtariPreprocessing(gym.make("MsPacmanNoFrameskip-v4", render_mode="rgb_array"), terminal_on_life_loss=True), -1, 1) # as recommended by the original paper, should already include max pooling
# env = gym.make("environments/TicTacToe-v0")
env = gym.wrappers.FrameStack(env, 4)

config = {
        'activation': 'relu',
        'kernel_initializer': 'orthogonal',
        'optimizer_function': tf.keras.optimizers.legacy.Adam,
        'learning_rate': 0.2,
        'adam_epsilon': 1e-7,
        'clipnorm': 0.5,
        # NORMALIZATION?
        # REWARD CLIPPING
        'num_epochs': 30,
        'num_filters': 256,
        'kernel_size': 3,
        'stride': 1,
        'num_res_blocks': 5,
        'critic_hidden_filters': 256,
        'critic_dense_size': 256,
        'actor_hidden_filters': 256,
        'actor_dense_size': 256,
        'memory_size': 10000,
        'max_game_length': 1000,
        'batch_size': 10,
        'dirichlet_alpha': 0.3,
        'dirichlet_epsilon': 0.25,
        'c_puct': 1,
        'monte_carlo_simulations': 10,
        'two_player': False,
    }    



A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]


In [5]:
agent = AlphaZeroAgent(env, config=config)
agent.train()

/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


Step 1
MCTS Simulation 0
MCTS Simulation 1
[0.26514965 0.05589323 0.09585019 0.10657643 0.09150373 0.06155779
 0.0659907  0.04658573 0.2108925 ] [0.4318971]
MCTS Simulation 2
[0.26343748 0.05609892 0.09604922 0.10784103 0.09207554 0.06168209
 0.06555466 0.04664026 0.21062085] [0.4277931]
MCTS Simulation 3
[0.2644186  0.05560083 0.09680771 0.1079082  0.09000997 0.0615611
 0.06648878 0.04705825 0.21014659] [0.41506007]
MCTS Simulation 4
[0.26343748 0.05609892 0.09604922 0.10784103 0.09207554 0.06168209
 0.06555466 0.04664026 0.21062085] [0.4277931]
MCTS Simulation 5
[0.25949216 0.05425709 0.09694357 0.11031099 0.0918166  0.06300046
 0.06700611 0.04688247 0.21029054] [0.43039235]
MCTS Simulation 6
[0.25949216 0.05425709 0.09694357 0.11031099 0.0918166  0.06300046
 0.06700611 0.04688247 0.21029054] [0.43039235]
MCTS Simulation 7
[0.26391152 0.05549599 0.09802141 0.10616675 0.09032156 0.06080491
 0.06623296 0.04647779 0.21256705] [0.4046145]
MCTS Simulation 8
[0.26285    0.05529787 0.097687

KeyboardInterrupt: 

In [ ]:
array = np.zeros((3, 9))
array[0] = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(array)

In [6]:
import gym_envs
import gymnasium as gym
env = gym.make('gym_envs/GridWorld-v0')

# env.reset()
# for i in range(10):
#     env.step(0)
#     env.render()


/Users/jonathanlamontange-kratz/Library/Python/3.9/lib/python/site-packages/gymnasium/envs/registration.py:481: UserWarning: WARN: The environment creator metadata doesn't include `render_modes`, contains: []
  logger.warn(


AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations