In [1]:
from elo import StandingsTable
import pandas as pd

# Example test data
players = ["Alice", "Bob", "Charlie"]

# Initialize StandingTable
table = StandingsTable(players, start_elo=1000)

table.add_player("David")  # Adding a new player

table.add_players(["Eve", "Frank"])  # Adding multiple players

table.add_result("David", "Eve", 1)  # David beats Eve

results_array = [
    ("Frank", "Alice", -1),  # Frank loses to Alice
    ("Bob", "David", 0),  # Bob draws with David
]
table.add_results_from_array(results_array)  # Adding multiple results

results = [
    ("Alice", "Bob", 1),  # Alice beats Bob
    ("Bob", "Charlie", 0),  # Bob draws with Charlie
    ("Charlie", "Alice", -1),  # Charlie loses to Alice
]
results_dataframe = pd.DataFrame(results, columns=["player1", "player2", "result"])
table.add_results_from_dataframe(results_dataframe)

win_table = table.get_win_table()
print("Win Table:\n", win_table)

draw_table = table.get_draw_table()
print("Draw Table:\n", draw_table)

elos = table.calculate_elos()
print("Elo Ratings:\n", elos)

bayes_elos = table.bayes_elo()
print("Bayesian Elo Ratings:\n", bayes_elos)

Win Table:
 [[0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Draw Table:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:15: RuntimeWarning: divide by zero encountered in log
  +0.5 * drawTable[i][j] * np.log(
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:15: RuntimeWarning: invalid value encountered in scalar multiply
  +0.5 * drawTable[i][j] * np.log(
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:7: RuntimeWarning: overflow encountered in power
  return 1.0 / (1 + np.power(10, D / 400))
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:14: RuntimeWarning: divide by zero encountered in log
  l += winTable[i][j] * np.log(f(elos[i] - elos[j] - eloAdvantage + eloDraw))
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:14: RuntimeWarning: invalid value encountered in scalar multiply
  l += winTable[i][j] * np.log(f(elos[i] - elos[j] - eloAdvantage + eloDraw))
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:15: RuntimeWarning: invalid va

Elo Ratings:
   message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: -24.590373584964087
        x: [ 1.018e+03  9.941e+02  9.941e+02  1.006e+03  9.941e+02
             9.941e+02 -2.350e+01  1.024e+03]
      nit: 1
      jac: [-1.723e-02  5.744e-03  5.744e-03 -5.744e-03  5.744e-03
             5.744e-03  2.298e-02 -2.298e-02]
 hess_inv: [[-1.965e+05  6.549e+04 ...  2.620e+05 -2.620e+05]
            [ 6.549e+04 -2.183e+04 ... -8.732e+04  8.732e+04]
            ...
            [ 2.620e+05 -8.732e+04 ... -3.493e+05  3.493e+05]
            [-2.620e+05  8.732e+04 ...  3.493e+05 -3.493e+05]]
     nfev: 1020
     njev: 112
Bayesian Elo Ratings:
 {'Elo table':           Elo Games  Score  Draws
Alice    1017     3    1.0    0.0
Bob       994     3  0.333  0.667
Charlie   994     2   0.25    0.5
David    1005     2   0.75    0.5
Eve       994     1    0.0    0.0
Frank     994     1    0.0    0.0, 'eloAdvantage': -23.50439453125, 'eloDraw

/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/elo/elo.py:15: RuntimeWarning: invalid value encountered in log
  +0.5 * drawTable[i][j] * np.log(
