1. Rainbow and Ape-X Expiriments 
    1. We release a set of hyper parameters for CartPole-v1 and Classic Control and Atari
    2. We release code for Rainbow that can train X steps in Y minutes on a Mac M2 Chip
    3. We also release a version of Ape-X as described in the original paper, and an Ape-X with rainbow
        1. Compare results of each 
        2. Compare Ape-X with different Rainbow components added or removed
    4. We compare the different models of DQN as seen in their papers to rainbow, the different individual components to rainbow, and rainbow with individual components removed
    10. Compare rainbow training speeds with different levels of numerical precision and datatypes
        1. Mixed precision using torch.amp 
        2. Lower matmul precision
            1. comparing medium, high, and highest 
            2. https://pytorch.org/docs/master/generated/torch.set_float32_matmul_precision.html?highlight=precision#torch.set_float32_matmul_precision
    11. Ape-X Hyper parameter sweep and sensitivities
    12. Exploration methods for Rainbow Ape-X
        1. Just noisy nets (same for all actors)
        2. Noisy nets and varying epsilon 
        3. Adding a constant that changes variance of noisy nets for action selection
        4. AlphaStar Agents

## Rainbow on CartPole-v1
Hyperparameters are based on the hyperopt experiments, quantized trial 27 with some minor changes

In [2]:
import gymnasium as gym
import sys

import torch
from utils import CategoricalCrossentropyLoss, KLDivergenceLoss
sys.path.append('../..')
from dqn.rainbow.rainbow_agent import RainbowAgent
from agent_configs import RainbowConfig
from game_configs import CartPoleConfig

env = gym.make("CartPole-v1", render_mode="rgb_array")

config_dict = {
  "dense_layers_widths": [128, 128],
  "value_hidden_layers_widths": [64, 64],
  "advatage_hidden_layers_widths": [64, 64],
  "adam_epsilon": 0.00375,
  "learning_rate": 0.005,
  "training_steps": 10000,
  "per_epsilon": 0.05,
  "per_alpha": 0.8,
  "per_beta": 0.45,
  "minibatch_size": 128,
  "replay_buffer_size": 10000,
  "min_replay_buffer_size": 1250,
  "transfer_interval": 10,
  "n_step": 9,
  "kernel_initializer": "glorot_uniform",
  "loss_function": KLDivergenceLoss(), # could do categorical cross entropy 
  "clipnorm": 2.0,
  "discount_factor": 0.99,
  "atom_size": 81,
  "replay_interval": 4,
}
game_config = CartPoleConfig()
config = RainbowConfig(config_dict, game_config)
device = "cuda:0" if torch.cuda.is_available() else "cpu"
agent = RainbowAgent(env, config, name="Rainbow_CartPole-v1", device=device)

for param in agent.model.parameters():
  print(param)
print("start")
agent.train()

Using default save_intermediate_weights     : False
Using         training_steps                : 10000
Using         adam_epsilon                  : 0.00375
Using         learning_rate                 : 0.005
Using         clipnorm                      : 2.0
Using default optimizer                     : <class 'torch.optim.adam.Adam'>
Using         loss_function                 : <utils.utils.KLDivergenceLoss object at 0x107cc52a0>
Using default activation                    : relu
Using         kernel_initializer            : glorot_uniform
Using         minibatch_size                : 128
Using         replay_buffer_size            : 10000
Using         min_replay_buffer_size        : 1250
Using default num_minibatches               : 1
Using default training_iterations           : 1
Using default conv_layers                   : []
Using         dense_layers_widths           : [128, 128]
Using         value_hidden_layers_widths    : [64, 64]
Using default advantage_hidden_layers_wid

/opt/homebrew/lib/python3.10/site-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/experiments/rainbow_and_ape-x folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(
/opt/homebrew/lib/python3.10/site-packages/gymnasium/core.py:311: UserWarning: WARN: env.lz4_compress to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.lz4_compress` for environment variables or `env.get_wrapper_attr('lz4_compress')` that will search the reminding wrappers.
  logger.warn(


[ 0.0296087  -0.02418866 -0.03774429  0.03534472]
[ 0.02912493 -0.21874958 -0.03703739  0.31588405]
[ 0.02474994 -0.41332495 -0.03071971  0.59666044]
[ 0.01648344 -0.60800385 -0.0187865   0.8795108 ]
[ 0.01026206 -0.3416236  -0.01292694  0.5506062 ]
[1.5409857]
[ 0.00432336 -0.80286556 -0.00119629  1.1662289 ]
[-0.01173395 -0.99797195  0.02212829  1.4585365 ]
[-0.03169338 -1.1933582   0.05129902  1.7580494 ]
[-0.05556055 -1.3890224   0.08646001  2.0662348 ]
[ 0.01319738 -0.14676611 -0.01820132  0.2637193 ]
[0.76715583]
[-0.083341  -1.1948804  0.1277847  1.8014972]
[-0.10723861 -1.0013976   0.16381465  1.551106  ]
[-0.12726656 -0.80857563  0.19483677  1.3136915 ]
[-0.01911015 -0.04771389  0.0203538   0.04113748]
[ 0.01223544  0.04809707 -0.01773501 -0.02331571]
[0.91538107]
[-0.02006443 -0.2431217   0.02117655  0.3401721 ]
[-0.02492686 -0.43853846  0.02797999  0.6394569 ]
[-0.03369763 -0.6340391   0.04076913  0.9408182 ]
[-0.04637842 -0.82968616  0.0595855   1.2460277 ]
[ 0.01518242 -0.

KeyboardInterrupt: 

## Rainbow on Classic Control
Hyperparameters come from revisitting rainbow

In [ ]:
import gymnasium as gym
import sys
import torch 

from utils import CategoricalCrossentropyLoss, KLDivergenceLoss
sys.path.append('../..')
from dqn.rainbow.rainbow_agent import RainbowAgent
from agent_configs import RainbowConfig
from game_configs import ClassicControlConfig

config_dict = {
  "dense_layers_widths": [512, 512],
  "value_hidden_layers_widths": [], # 
  "advatage_hidden_layers_widths": [], # 
  "adam_epsilon": 3.125e-4,
  "learning_rate": 0.001,
  "training_steps": 30000,
  "per_epsilon": 1e-6, # 
  "per_alpha": 0.5,
  "per_beta": 0.5, # For RIAYN should be no annealing # 0.4
  "minibatch_size": 128,
  "replay_buffer_size": 50000,
  "min_replay_buffer_size": 500,
  "transfer_interval": 100,
  "n_step": 3,
  "kernel_initializer": "orthogonal", #
  "loss_function": KLDivergenceLoss(), # KLDivergence()
  "clipnorm": 0.0, # 2.0 
  "discount_factor": 0.99,
  "atom_size": 51,
  "replay_interval": 2,
}
game_config = ClassicControlConfig()
config = RainbowConfig(config_dict, game_config)
device = "cuda:0" if torch.cuda.is_available() else "cpu"

# game_config.v_min = 0
# game_config.v_max = 500
# env = gym.make("CartPole-v1", render_mode="rgb_array")
# agent = RainbowAgent(env, config, name="Rainbow_ClassicControl_CartPole-v1", device=device)
# agent.train()

# game_config.v_min = -500
# game_config.v_max = 0
# env = gym.make("Acrobot-v1", render_mode="rgb_array")
# agent = RainbowAgent(env, config, name="Rainbow_ClassicControl_Acrobot-v1", device=device)
# agent.train()

# game_config.v_min = -200
# game_config.v_max = 200
# env = gym.make("LunarLander-v2", render_mode="rgb_array")
# agent = RainbowAgent(env, config, name="Rainbow_ClassicControl_LunarLander-v2", device=device)
# agent.train()

# game_config.v_min = -200
# game_config.v_max = -100
env = gym.make("MountainCar-v0", render_mode="rgb_array", max_episode_steps=600)
agent = RainbowAgent(env, config, name="Rainbow_ClassicControl_MountainCar-v0", device=device)
agent.train()

## Rainbow on Atari
Takes around 18GB RAM, and many hours even just to fill replay buffer with a Mac M2

### Rainbow MsPacman

In [1]:
import gymnasium as gym
import sys

from utils import CategoricalCrossentropyLoss, KLDivergenceLoss
sys.path.append('../..')
from dqn.rainbow.rainbow_agent import RainbowAgent
from agent_configs import RainbowConfig
from game_configs import AtariConfig
from gymnasium.wrappers import AtariPreprocessing, FrameStack
import numpy as np

config_dict = {
  "conv_layers": [
      (32, 8, 4),
      (64, 4, 2),
      (64, 3, 1),
  ],
  "dense_layers_widths": [512], 
  "value_hidden_layers_widths": [], # 
  "advatage_hidden_layers_widths": [], # 
  "adam_epsilon": 1.5e-4,
  "learning_rate": 0.00025/4,
  "training_steps": 50000000, # Agent saw 200,000,000 frames
  "per_epsilon": 1e-6, # 
  "per_alpha": 0.5, 
  "per_beta": 0.4, 
  "minibatch_size": 32,
  "replay_buffer_size": 1000000,
  "min_replay_buffer_size": 80000,
  "transfer_interval": 32000,
  "n_step": 3,
  "kernel_initializer": "orthogonal", #
  "loss_function": KLDivergenceLoss(),
  "clipnorm": 0.0, # 
  "discount_factor": 0.99,
  "atom_size": 51,
  "replay_interval": 4,
}
game_config = AtariConfig()
config = RainbowConfig(config_dict, game_config)

class ClipReward(gym.RewardWrapper):
    def __init__(self, env, min_reward, max_reward):
        super().__init__(env)
        self.min_reward = min_reward
        self.max_reward = max_reward
        self.reward_range = (min_reward, max_reward)

    def reward(self, reward):
        return np.clip(reward, self.min_reward, self.max_reward)
    
env = gym.make("MsPacmanNoFrameskip-v4", render_mode="rgb_array", max_episode_steps=108000)
env = AtariPreprocessing(env, terminal_on_life_loss=True)
env = FrameStack(env, 4, lz4_compress=True)
agent = RainbowAgent(env, config, name="Rainbow_Atari_MsPacmanNoFrameskip-v4")
agent.checkpoint_interval = 1000
agent.train()

Using default save_intermediate_weights     : False
Using         training_steps                : 50000000
Using         adam_epsilon                  : 0.00015
Using         learning_rate                 : 6.25e-05
Using         clipnorm                      : 0.0
Using default optimizer                     : <class 'torch.optim.adam.Adam'>
Using         loss_function                 : <utils.utils.KLDivergenceLoss object at 0x107cc73a0>
Using default activation                    : relu
Using         kernel_initializer            : orthogonal
Using         minibatch_size                : 32
Using         replay_buffer_size            : 1000000
Using         min_replay_buffer_size        : 80000
Using default num_minibatches               : 1
Using default training_iterations           : 1
Using         conv_layers                   : [(32, 8, 4), (64, 4, 2), (64, 3, 1)]
Using         dense_layers_widths           : [512]
Using         value_hidden_layers_widths    : []
Using default 

A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
/opt/homebrew/lib/python3.10/site-packages/gymnasium/wrappers/record_video.py:94: UserWarning: WARN: Overwriting existing videos at /Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/experiments/rainbow_and_ape-x folder (try specifying a different `video_folder` for the `RecordVideo` wrapper if this is not desired)
  logger.warn(


observation_dimensions:  (4, 84, 84)
num_actions:  9
uint8
0
0


KeyboardInterrupt: 

## Rainbow with  turn-based zero-sum 2-player perfect information deterministic games
Not working yet because of zero sum rewards, could get it to work by doing an NFSP sort of thing when storing experiences

### Rainbow Tic Tac Toe

#### Framestacking

In [ ]:
import gymnasium as gym
import sys

from packages.game_configs.game_configs.tictactoe_config import TicTacToeConfig
from utils import CategoricalCrossentropyLoss, KLDivergenceLoss
sys.path.append('../..')
from dqn.rainbow.rainbow_agent import RainbowAgent
from agent_configs import RainbowConfig
from game_configs import AtariConfig
from gymnasium.wrappers import AtariPreprocessing, FrameStack
import numpy as np

config_dict = {
  "conv_layers": [
      (32, 8, 4),
      (64, 4, 2),
      (64, 3, 1),
  ],
  "dense_layers_widths": [512], 
  "value_hidden_layers_widths": [], # 
  "advatage_hidden_layers_widths": [], # 
  "adam_epsilon": 1.5e-4,
  "learning_rate": 0.00025/4,
  "training_steps": 50000000, # Agent saw 200,000,000 frames
  "per_epsilon": 1e-6, # 
  "per_alpha": 0.5, 
  "per_beta": 0.4, 
  "minibatch_size": 32,
  "replay_buffer_size": 1000000,
  "min_replay_buffer_size": 80000,
  "transfer_interval": 32000,
  "n_step": 3,
  "kernel_initializer": "orthogonal", #
  "loss_function": KLDivergenceLoss(),
  "clipnorm": 0.0, # 
  "discount_factor": 0.99,
  "atom_size": 51,
  "replay_interval": 4,
}
game_config = TicTacToeConfig()
config = RainbowConfig(config_dict, game_config)

env = gym.make("TicTacToe-v0", render_mode="rgb_array")
env = FrameStack(env, 4)
agent = RainbowAgent(env, config, name="Rainbow_TicTacToe-v0")
agent.train()

#### No framestacking

In [ ]:
import gymnasium as gym
import sys

from packages.game_configs.game_configs.tictactoe_config import TicTacToeConfig
from utils import CategoricalCrossentropyLoss, KLDivergenceLoss
sys.path.append('../..')
from dqn.rainbow.rainbow_agent import RainbowAgent
from agent_configs import RainbowConfig
from game_configs import AtariConfig
from gymnasium.wrappers import AtariPreprocessing, FrameStack
import numpy as np

config_dict = {
  "conv_layers": [
      (32, 8, 4),
      (64, 4, 2),
      (64, 3, 1),
  ],
  "dense_layers_widths": [512], 
  "value_hidden_layers_widths": [], # 
  "advatage_hidden_layers_widths": [], # 
  "adam_epsilon": 1.5e-4,
  "learning_rate": 0.00025/4,
  "training_steps": 50000000, # Agent saw 200,000,000 frames
  "per_epsilon": 1e-6, # 
  "per_alpha": 0.5, 
  "per_beta": 0.4, 
  "minibatch_size": 32,
  "replay_buffer_size": 1000000,
  "min_replay_buffer_size": 80000,
  "transfer_interval": 32000,
  "n_step": 3,
  "kernel_initializer": "orthogonal", #
  "loss_function": KLDivergenceLoss(),
  "clipnorm": 0.0, # 
  "discount_factor": 0.99,
  "atom_size": 51,
  "replay_interval": 4,
}
game_config = TicTacToeConfig()
config = RainbowConfig(config_dict, game_config)

env = gym.make("TicTacToe-v0", render_mode="rgb_array")
agent = RainbowAgent(env, config, name="Rainbow_TicTacToe-v0")
agent.train()

### Rainbow Connect 4

### Rainbow Chess