In [ ]:
from collections import deque
test = deque(maxlen=2)
state = 1 
test.append(state)
action = 0
done = False
state = 2
test.append(state)
action = 2
done = True
state = 3
for p in range(len(test)):
    print(p)
    print(test[p], action, 0, test[-p + 1], done)  
print(test)


In [1]:
from nfsp_agent import NFSPDQN

In [2]:
from agent_configs import NFSPDQNConfig, RainbowConfig
from game_configs import MississippiMarblesConfig, LeducHoldemConfig
from utils import KLDivergenceLoss, CategoricalCrossentropyLoss

config_dict = {
    "activation": "relu",
    "kernel_initializer": "he_normal",
    "loss_function": KLDivergenceLoss(),
    "sl_loss_function": CategoricalCrossentropyLoss(),
    "per_epsilon": 0.01,
    "sl_activation": "relu",
    "sl_kernel_initializer": "he_normal",
    "num_players": 2,
    "training_steps": 20000,
    "anticipatory_param": 0.1,
    "min_replay_buffer_size": 16,
    "sl_min_replay_buffer_size": 16,
    "minibatch_size": 16,
    "sl_minibatch_size": 16,
    "replay_interval": 32,
    "sl_replay_buffer_size": 2000000,
    "replay_buffer_size": 200000,
    "transfer_interval": 100,
    "n_step": 1,
    "learning_rate": 0.0005,
}
# config = NFSPConfig(config_dict=config_dict, game_config=MississippiMarblesConfig(), rl_config_type=RainbowConfig)
config = NFSPDQNConfig(config_dict=config_dict, game_config=LeducHoldemConfig(), rl_config_type=RainbowConfig)

Using default save_intermediate_weights     : False
Using         training_steps                : 20000
Using default adam_epsilon                  : 1e-06
Using default learning_rate                 : 0.001
Using default clipnorm                      : 0
Using default optimizer                     : <class 'torch.optim.adam.Adam'>
Using         loss_function                 : <utils.utils.KLDivergenceLoss object at 0x295ce9ff0>
Using         activation                    : relu
Using         kernel_initializer            : he_normal
Using         minibatch_size                : 16
Using         replay_buffer_size            : 200000
Using         min_replay_buffer_size        : 16
Using default num_minibatches               : 1
Using default training_iterations           : 1
Using         num_players                   : 2
Using default save_intermediate_weights     : False
Using         training_steps                : 20000
Using default adam_epsilon                  : 1e-06
Using def

In [5]:
import custom_gym_envs
import gymnasium as gym
# env = gym.make('custom_gym_envs/MississippiMarbles-v0', render_mode="human", players=2)
env = gym.make('custom_gym_envs/LeducHoldem-v0')
agent = NFSPDQN(env, config, "cpu")

observation_dimensions:  (36,)
num_actions:  4
observation_dimensions:  (36,)
num_actions:  4
observation_dimensions:  (36,)
num_actions:  4
int8
observation_dimensions:  (36,)
num_actions:  4
observation_dimensions:  (36,)
num_actions:  4
observation_dimensions:  (36,)
num_actions:  4
int8
observation_dimensions:  (36,)
num_actions:  4


In [6]:
agent.checkpoint_trials = 100
agent.train()

/opt/homebrew/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be int8, actual type: float64
  logger.warn(
/opt/homebrew/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/opt/homebrew/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:135: UserWarning: WARN: The obs returned by the `step()` method was expecting numpy array dtype to be int8, actual type: float64
  logger.warn(
/opt/homebrew/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:159: UserWarning: WARN: The obs returned by the `step()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/opt/homebrew/lib/python3.10/site-packages/gymnasium/utils

tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0 0
tensor([1., 0.

/opt/homebrew/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:246: UserWarning: WARN: The reward returned by `step()` must be a float, int, np.integer or np.floating, actual type: <class 'numpy.ndarray'>
  logger.warn(
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/packages/utils/utils/utils.py:257: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  axs[row][col].legend()
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/packages/utils/utils/utils.py:187: UserWarning: Attempting to set identical low and high xlims makes transformation singular; automatically expanding.
  axs[row][col].set_xlim(1, len(values))
/Users/jonathanlamontange-kratz/Documents/GitHub/rl-stuff/packages/utils/utils/utils.py:207: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored wh

tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.11392858624458313 tensor(8.9729)
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0
0.14565715193748474 tensor(8.0206)
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.060814909636974335 tensor(5.2041)
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.07845943421125412 tensor(6.0610)
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.1301812082529068 tensor(7.9809)
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0
0.16020292043685913 tensor(9.8192)
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.07466258853673935 tensor(6.2642)
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.1979617178440094 tensor(5.9542)
tensor([0., 1., 0., 0.])
torch.Size([4])
(2000000, 4)
0
0.1607980728149414 tensor(8.1122)
tensor([1., 0., 0., 0.])
torch.Size([4])
(2000000, 4)
0
0.06417148560285568 tensor(3.0484)
tensor([0., 0., 1., 0.])
torch.Size([4])
(2000000, 4)
0
0.1551787257194519 tensor(4.3194)
te

KeyboardInterrupt: 